apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    kubernetes.io/change-cause: "create pod api"
  name: api-twitter-demo
  labels:
    app: twitter-demo
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: twitter-demo
  template:
    metadata:
      labels:
        app: twitter-demo
    spec:
      containers:
        - name: twitter-demo
          image: jonarosero/golang-api-twitter-demo
          ports:
          - containerPort: 8080
          env: 
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-twitter-demo
  labels:
    app: twitter-demo
spec:
  type: LoadBalancer
  selector:
    app: twitter-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080